version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - GEMINI_API_KEY=${AIzaSyC9V9qNG7Z1w1L8FHeWxyJX7owUD7RoRD0}
      - DATABASE_URL=postgres://user:password@db:5432/your_database
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
